name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: create build directory
      run: cd csrc && mkdir build
    - name: cmake generate
      run: cd csrc/build && cmake ..
    - name: make
      run: cd csrc/build && make
    - name: make check
      run: cd csrc/build && make check
    - name: cd csrc/build && make distcheck
      run: make distcheck
